#!/bin/sh

I2C_BUS=1
case "$1" in
  start)
    echo "Starting I2C for LSM9DS1"
    modprobe i2c-bcm2835
    modprobe i2c-dev
    sleep 0.5
    ;;
    
  stop)
    echo "Stopping I2C"
    modprobe -r i2c-dev i2c-bcm2835
    ;;
    
  restart)
    $0 stop
    $0 start
    ;;
    
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
